export const CompanyConfig = {
    COMPANY_NAME_MIN_LENGTH: 5,
    COMPANY_NAME_MAX_LENGTH: 80,
    TRADING_NAME_MIN_LENGTH: 5,
    TRADING_NAME_MAX_LENGTH: 80,
    ZIPCODE_MAX_LENGTH: 20,
    REGISTER_NUMBER_MIN_LENGTH: 3,
    REGISTER_NUMBER_MAX_LENGTH: 30
}
