export const UserConfig = {
    USER_NAME_MIN_LENGTH: 4,
    USER_NAME_MAX_LENGTH: 80,
    USER_LOGIN_MIN_LENGTH: 4,
    USER_LOGIN_MAX_LENGTH: 20,
    USER_PASSWORD_MIN_LENGTH: 6,
    USER_PASSWORD_MAX_LENGTH: 20,
    USER_EMAIL_MAX_LENGTH: 50
}
